[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  # Disable secrets scanning since we're using proper server-side functions
  SECRETS_SCAN_ENABLED = "false"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200